changelog:
  categories:
    - title: Enhancement
      labels:
        - enhancement
    - title: Bug Fix
      labels:
        - bug
        - fixes
  exclude:
    labels:
        - dependencies
    authors:
        - dependabot