name: Conditions
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello"
        if: ${{ contains(github.run_id, '1') }}
  fail:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
      - run: echo "This proccess is Error!"
        if: ${{ failure() }}
  skip-or-run:
    if: ${{ github.actor == 'octocat' }}
    runs-on: ubuntu-latest
    steps:
        - name: Amazing Script
          run: echo "Hello"
